[package]
name = "unsplash-wally"
version = "0.1.0"
description = "A beautiful wallpaper manager using Unsplash"
authors = ["you"]
edition = "2021"

[lib]
name = "unsplash_wally_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
dirs = "5"
chrono = { version = "0.4", features = ["serde"] }
open = "5"
tauri-plugin-os = "2.3.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = ["Win32_UI_Shell", "Win32_System_Com", "Win32_Foundation"] }
